name: Deploy to Maven Central

on:
  push:
    tags:
      - '*.*.*'  # 触发条件：v1.2.3 等标签

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}

      - name: Extract version from tag
        id: tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set version in pom.xml
        run: mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false -DprocessAllModules=true

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" > private.key
          gpg --batch --import private.key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>" > ~/.m2/settings.xml
          echo "  <servers>" >> ~/.m2/settings.xml
          echo "    <server>" >> ~/.m2/settings.xml
          echo "      <id>ossrh</id>" >> ~/.m2/settings.xml
          echo "      <username>${{ secrets.OSSRH_USERNAME }}</username>" >> ~/.m2/settings.xml
          echo "      <password>${{ secrets.OSSRH_TOKEN }}</password>" >> ~/.m2/settings.xml
          echo "    </server>" >> ~/.m2/settings.xml
          echo "  </servers>" >> ~/.m2/settings.xml
          echo "</settings>" >> ~/.m2/settings.xml

      - name: Deploy to OSSRH
        run: mvn clean deploy -P release -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
